#Minecraft server properties
#Thu Oct 03 16:33:02 UTC 2024
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=normal
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=30
max-tick-time=30000
max-world-size=29999984
motd=§x§f§f§6§6§0§0E§x§f§f§5§f§1§1p§x§f§f§5§8§2§2i§x§f§f§5§2§3§3c§x§f§f§4§b§4§4 §x§f§f§4§4§5§5R§x§f§f§3§d§6§6e§x§f§f§3§6§7§7a§x§f§f§3§0§8§8l§x§f§f§2§9§9§9m§x§f§f§2§2§a§as§x§f§f§1§b§b§b §x§f§f§1§4§c§cS§x§f§f§0§e§d§dM§x§f§f§0§7§e§eP §x§f§f§0§0§2§8W§x§f§c§0§9§2§7h§x§f§9§1§2§2§5e§x§f§6§1§b§2§4r§x§f§4§2§4§2§2e§x§f§1§2§e§2§1 §x§e§e§3§7§1§fF§x§e§b§4§0§1§er§x§e§8§4§9§1§di§x§e§5§5§2§1§be§x§e§2§5§b§1§an§x§e§0§6§4§1§8d§x§d§d§6§d§1§7s§x§d§a§7§6§1§5 §x§d§7§8§0§1§4B§x§d§4§8§9§1§3e§x§d§1§9§2§1§1c§x§c§e§9§b§1§0o§x§c§c§a§4§0§em§x§c§9§a§d§0§de§x§c§6§b§6§0§b §x§c§3§b§f§0§aL§x§c§0§c§8§0§9e§x§b§d§d§1§0§7g§x§b§a§d§b§0§6e§x§b§8§e§4§0§4n§x§b§5§e§d§0§3d§x§b§2§f§6§0§1s §x§0§0§e§4§f§fJ§x§0§9§e§3§f§6o§x§1§3§e§2§e§ci§x§1§c§e§1§e§3n§x§2§6§e§0§d§9 §x§2§f§d§f§d§0F§x§3§9§d§e§c§6o§x§4§2§d§d§b§dr§x§4§c§d§c§b§3 §x§5§5§d§b§a§aT§x§5§e§d§a§a§1h§x§6§8§d§9§9§7e§x§7§1§d§8§8§e §x§7§b§d§7§8§4E§x§8§4§d§6§7§bp§x§8§e§d§5§7§1i§x§9§7§d§4§6§8c§x§a§1§d§3§5§e §x§a§a§d§2§5§5A§x§b§3§d§1§4§cd§x§b§d§d§0§4§2v§x§c§6§c§f§3§9e§x§d§0§c§e§2§fn§x§d§9§c§d§2§6t§x§e§3§c§c§1§cu§x§e§c§c§b§1§3r§x§f§6§c§a§0§9e
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://download.mc-packs.net/pack/8135f14ac955bb64fd521b437e9ce24abf64ed42.zip
resource-pack-id=epic-realms-smp-resource-pack
resource-pack-prompt=&l&8[&6Epic Realms SMP Resource Pack - Enhance Your Adventure&l&8]
resource-pack-sha1=8135f14ac955bb64fd521b437e9ce24abf64ed42
server-ip=
server-port=25565
simulation-distance=32
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=70
sync-chunk-writes=false
text-filtering-config=
use-native-transport=true
view-distance=32
white-list=false
