#Minecraft server properties
#Mon Oct 07 10:20:58 UTC 2024
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=normal
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=30
max-tick-time=30000
max-world-size=29999984
motd=§x§f§f§6§6§0§0E§x§f§f§6§0§0§fp§x§f§f§5§a§1§ei§x§f§f§5§4§2§dc§x§f§f§4§e§3§c §x§f§f§4§8§4§bR§x§f§f§4§2§5§ae§x§f§f§3§c§6§9a§x§f§f§3§6§7§8l§x§f§f§3§0§8§7m§x§f§f§2§a§9§6s§x§f§f§2§4§a§5 §x§f§f§1§e§b§4S§x§f§f§1§8§c§3M§x§f§f§1§2§d§2P§x§f§f§0§c§e§1 §x§f§f§0§6§f§0- §x§1§4§f§f§0§0W§x§1§3§f§9§0§9h§x§1§3§f§2§1§2e§x§1§2§e§c§1§ar§x§1§1§e§5§2§3e§x§1§1§d§f§2§c §x§1§0§d§8§3§5F§x§0§f§d§2§3§er§x§0§e§c§b§4§6i§x§0§e§c§5§4§fe§x§0§d§b§e§5§8n§x§0§c§b§8§6§1d§x§0§c§b§1§6§as§x§0§b§a§b§7§2 §x§0§a§a§4§7§bB§x§0§a§9§e§8§4e§x§0§9§9§7§8§dc§x§0§8§9§1§9§5o§x§0§8§8§a§9§em§x§0§7§8§4§a§7e§x§0§6§7§d§b§0 §x§0§6§7§7§b§9L§x§0§5§7§0§c§1e§x§0§4§6§a§c§ag§x§0§3§6§3§d§3e§x§0§3§5§d§d§cn§x§0§2§5§6§e§5d§x§0§1§5§0§e§ds§x§0§1§4§9§f§6\! §x§f§f§0§0§0§0-§x§f§f§0§8§0§0 §x§f§f§1§0§0§0J§x§f§f§1§8§0§0o§x§f§f§2§0§0§0i§x§f§f§2§8§0§0n§x§f§f§3§0§0§0 §x§f§f§3§8§0§0T§x§f§f§4§0§0§0h§x§f§f§4§8§0§0e§x§f§f§5§0§0§0 §x§f§f§5§8§0§0U§x§f§f§6§0§0§0l§x§f§f§6§8§0§0t§x§f§f§7§0§0§0i§x§f§f§7§9§0§0m§x§f§f§8§1§0§0a§x§f§f§8§9§0§0t§x§f§f§9§1§0§0e§x§f§f§9§9§0§0 §x§f§f§a§1§0§0A§x§f§f§a§9§0§0d§x§f§f§b§1§0§0v§x§f§f§b§9§0§0e§x§f§f§c§1§0§0n§x§f§f§c§9§0§0t§x§f§f§d§1§0§0u§x§f§f§d§9§0§0r§x§f§f§e§1§0§0e§x§f§f§e§9§0§0\!
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://download.mc-packs.net/pack/8135f14ac955bb64fd521b437e9ce24abf64ed42.zip
resource-pack-id=epic-realms-smp-resource-pack
resource-pack-prompt=§x§f§f§c§a§0§0E§x§f§f§c§8§0§2p§x§f§f§c§6§0§4i§x§f§f§c§4§0§7c§x§f§f§c§2§0§9 §x§f§f§c§0§0§bR§x§f§f§b§e§0§de§x§f§f§b§c§0§fa§x§f§f§b§a§1§1l§x§f§f§b§8§1§4m§x§f§f§b§6§1§6s§x§f§f§b§4§1§8 §x§f§f§b§2§1§aS§x§f§f§a§f§1§cM§x§f§f§a§d§1§eP§x§f§f§a§b§2§1 §x§f§f§a§9§2§3R§x§f§f§a§7§2§5e§x§f§f§a§5§2§7s§x§f§f§a§3§2§9o§x§f§f§a§1§2§bu§x§f§f§9§f§2§er§x§f§f§9§d§3§0c§x§f§f§9§b§3§2e§x§f§f§9§9§3§4 §x§f§f§9§7§3§6P§x§f§f§9§5§3§8a§x§f§f§9§3§3§bc§x§f§f§9§1§3§dk§x§f§f§8§f§3§f §x§f§f§8§d§4§1-§x§f§f§8§b§4§3 §x§f§f§8§9§4§5E§x§f§f§8§7§4§8n§x§f§f§8§5§4§ah§x§f§f§8§3§4§ca§x§f§f§8§1§4§en§x§f§f§7§f§5§0c§x§f§f§7§c§5§3e§x§f§f§7§a§5§5 §x§f§f§7§8§5§7Y§x§f§f§7§6§5§9o§x§f§f§7§4§5§bu§x§f§f§7§2§5§dr§x§f§f§7§0§6§0 §x§f§f§6§e§6§2A§x§f§f§6§c§6§4d§x§f§f§6§a§6§6v§x§f§f§6§8§6§8e§x§f§f§6§6§6§an§x§f§f§6§4§6§dt§x§f§f§6§2§6§fu§x§f§f§6§0§7§1r§x§f§f§5§e§7§3e§x§f§f§5§c§7§5 §x§f§f§5§a§7§7-§x§f§f§5§8§7§a §x§f§f§5§6§7§cY§x§f§f§5§4§7§eo§x§f§f§5§2§8§0u§x§f§f§5§0§8§2 §x§f§f§4§e§8§4m§x§f§f§4§b§8§7u§x§f§f§4§9§8§9s§x§f§f§4§7§8§bt§x§f§f§4§5§8§d §x§f§f§4§3§8§fa§x§f§f§4§1§9§2c§x§f§f§3§f§9§4c§x§f§f§3§d§9§6e§x§f§f§3§b§9§8p§x§f§f§3§9§9§at§x§f§f§3§7§9§c §x§f§f§3§5§9§ft§x§f§f§3§3§a§1h§x§f§f§3§1§a§3e§x§f§f§2§f§a§5 §x§f§f§2§d§a§7R§x§f§f§2§b§a§9e§x§f§f§2§9§a§cs§x§f§f§2§7§a§eo§x§f§f§2§5§b§0u§x§f§f§2§3§b§2r§x§f§f§2§1§b§4c§x§f§f§1§f§b§6e§x§f§f§1§d§b§9 §x§f§f§1§b§b§bP§x§f§f§1§8§b§da§x§f§f§1§6§b§fc§x§f§f§1§4§c§1k§x§f§f§1§2§c§3 §x§f§f§1§0§c§6t§x§f§f§0§e§c§8o§x§f§f§0§c§c§a §x§f§f§0§a§c§cP§x§f§f§0§8§c§el§x§f§f§0§6§d§0a§x§f§f§0§4§d§3y§x§f§f§0§2§d§5\!
resource-pack-sha1=8135f14ac955bb64fd521b437e9ce24abf64ed42
server-ip=
server-port=25565
simulation-distance=32
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=70
sync-chunk-writes=false
text-filtering-config=
use-native-transport=true
view-distance=32
white-list=false
