name: Update Server Jar

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-server-jar:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Remove specified folders
      - name: Remove folders
        run: |
          for folder in cache libraries logs versions; do
            if [ -d "$folder" ]; then
              git rm -r --cached "$folder"
              echo "Removed $folder"
            else
              echo "$folder does not exist"
            fi
          done

      # Commit changes
      - name: Commit changes
        run: |
          git commit -m "Remove cache/, libraries/, logs/, and versions/ folders"

      # Push changes
      - name: Push changes
        run: git push
