name: Update Server Jar

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-server-jar:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Rename plugins
      - name: Rename plugin files
        run: |
          cd plugins
          mv TreeFeller-1.24.1.jar TreeFeller.jar
          mv SpawnerSilk-5.8.0.jar SpawnerSilk.jar

      # Commit changes
      - name: Commit changes
        run: |
          git add plugins/
          git commit -m "Update and rename plugin files in the plugins/ folder"

      # Push changes
      - name: Push changes
        run: git push
