name: Update Server Jar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-server-jar:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Remove the existing server.jar
      - name: Remove old server.jar
        run: |
          if [ -f server.jar ]; then
            git rm server.jar
            echo "Removed old server.jar"
          else
            echo "No server.jar to remove"
          fi

      # Download the new PaperMC server.jar
      - name: Download new server.jar
        run: |
          curl -o server.jar https://api.papermc.io/v2/projects/paper/versions/1.21.3/builds/29/downloads/paper-1.21.3-29.jar
          echo "Downloaded new server.jar"

      # Commit changes
      - name: Commit changes
        run: |
          git add server.jar
          git commit -m "Update server.jar to Paper 1.21.3 build 29"

      # Push changes
      - name: Push changes
        run: git push
